services:
  personal-image-generator:
    image: ghcr.io/huge1818666/personal-mobile-image-generator:latest
    container_name: personal-image-generator
    restart: unless-stopped
    ports:
      - "4273:4273"
    environment:
      APP_USERNAME: personal
      APP_PASSWORD: personal123456
    volumes:
      - ./data:/data
